Algoritmo "Distancia"

Var

   x, y, z : real
   

Inicio

   escreva ("Distancia X: ")
   leia (x)
   escreva ("Distancia Y: ")
   leia (y)
   escreva ("Distancia Z: ")
   leia (z)
   
   se (x > y) e (x > z) entao
      escreval ("Maior distância é: ", x:4:2)
   senao
      se (y > Z) entao
         escreval ("Maior distância é : ", y:4:2)
      senao
      escreval ("Maior distancia é : ", z:4:2)
      fimse
   fimse



Fimalgoritmo